---
- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic
- name: Install Kibana
  hosts: kibana
  roles:
    - kibana
- name: Install Filebeat
  hosts: filebeat
  roles:
    - filebeat